# Site settings
# accessible in the templates via {{ site.myvariable }}.
title: MasterWP
description: "Your exciting weekly email with apps, tools and links that will make your life better. Do you work with WordPress? Sign up and enjoy the email."

baseurl: "" # the subpath of your site, e.g. /blog
url: https://masterwp.co # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: binarymoon
github_username: binarymoon
github: [metadata]
repository: BinaryMoon/MasterWP
permalink: /blog/:year/:title/
google_analytics: UA-55722-24
logo: /assets/images/favicon-192.png
subscribers: "3,513"
enable_countdown: true

# Build settings
markdown: kramdown

# SEO
twitter:
  username: binarymoon
#webmaster_verifications:
#  google: jpX5pDZ1_vsfHTm74TkvqTO5U5hjbpzsj6gnjuVeQXs

# Collections
collections:
  themes:
    output: true
    permalink: /wordpress-themes/:name/
  theme-developers:
    output: true
    permalink: /wordpress-theme-developers/:name/
  events:
    output: false
    sort_by: date_start

# Default properties
defaults:
  - scope:
      type: pages
    values:
      image: /assets/images/og-image.png
  - scope:
      type: themes
    values:
      layout: theme
  - scope:
      type: theme-developers
    values:
      layout: theme-developer

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

include:
  - _pages
