# Site settings
# accessible in the templates via {{ site.myvariable }}.
title: MasterWP
description: >

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: prothemedesign
github_username:  binarymoon

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
